title: Pangolin Mode's Pokémon Report
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "poke.carlvanreis.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Pangolin Mode # add your name
author-img: Pangolin-Mode-Logo-Clean.png # add your photo
about-author: Working on building out this template # add description
social-twitter: carlvanr # add your Twitter handle
social-facebook: carl.vanreis # add your Facebook handle
social-github: pangolinmode # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: carlvanreis@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]